### ISSUE TITLE
Implement Loading component in each page(component)

### ISSUE THREAD

**Issue by rizafahmi** [rizafahmi/react-dds-courses#11]

**Comment by nidble** [comment]
Can I work on this?

**Comment by rizafahmi** [comment]
Sure @nidble! Thanks anyway!

**Comment by nidble** [comment]
Hi @rizafahmi,

When I include `Loading` component a warning message is showed up on the console:
`Line 58:  img elements must have an alt prop, either with meaningful text, or an empty string for decorative images  jsx-a11y/alt-text`

Because this is very easy to fix I can provide an alt tag with "Loading...". 

What do you think about?
Thanks
